import { contextBridge, ipcRenderer } from 'electron';

function subscribe(channel: string, handler: (value: unknown) => void): () => void {
  const listener = (_event: Electron.IpcRendererEvent, value: unknown) => handler(value);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('surprisedFace', {
  settings: () => ipcRenderer.invoke('app:settings'),
  updateSettings: (input: unknown) => ipcRenderer.invoke('app:update-settings', input),
  bootstrap: (input: unknown) => ipcRenderer.invoke('app:bootstrap', input),
  register: (name: string) => ipcRenderer.invoke('app:register', name),
  copyText: (value: string) => ipcRenderer.invoke('app:copy-text', value),
  join: (input: unknown) => ipcRenderer.invoke('app:join', input),
  joinRoom: (code: string) => ipcRenderer.invoke('app:join-room', code),
  logout: () => ipcRenderer.invoke('app:logout'),
  createInvites: (roomId: string) => ipcRenderer.invoke('app:create-invites', roomId),
  rooms: () => ipcRenderer.invoke('app:rooms'),
  createRoom: (input: unknown) => ipcRenderer.invoke('app:create-room', input),
  openRoom: (roomId: string) => ipcRenderer.invoke('app:open-room', roomId),
  roomMessages: (roomId: string) => ipcRenderer.invoke('app:room-messages', roomId),
  pendingMessages: (roomId: string) => ipcRenderer.invoke('app:pending-messages', roomId),
  sendMessage: (input: unknown) => ipcRenderer.invoke('app:send-message', input),
  members: (roomId: string) => ipcRenderer.invoke('app:members', roomId),
  agents: (roomId: string) => ipcRenderer.invoke('app:agents', roomId),
  saveAgent: (input: unknown) => ipcRenderer.invoke('app:save-agent', input),
  runPending: (roomId: string) => ipcRenderer.invoke('app:run-pending', roomId),
  chooseFolder: () => ipcRenderer.invoke('app:choose-folder'),
  sheepHealth: () => ipcRenderer.invoke('sheep:health'),
  sheepProjects: () => ipcRenderer.invoke('sheep:projects'),
  sheepConversations: () => ipcRenderer.invoke('sheep:conversations'),
  sheepRefresh: () => ipcRenderer.invoke('sheep:refresh'),
  sheepRead: (input: unknown) => ipcRenderer.invoke('sheep:read', input),
  sheepReadNative: (input: unknown) => ipcRenderer.invoke('sheep:read-native', input),
  sheepNativeRecords: (input: unknown) => ipcRenderer.invoke('sheep:native-records', input),
  nativeSend: (input: unknown) => ipcRenderer.invoke('native:send', input),
  nativeCreate: (input: unknown) => ipcRenderer.invoke('native:create', input),
  nativeLink: (input: unknown) => ipcRenderer.invoke('native:link', input),
  nativeShare: (input: unknown) => ipcRenderer.invoke('native:share', input),
  onNativeChatEvent: (handler: (value: unknown) => void) => subscribe('native:chat-event', handler),
  codexAccount: (refresh?: boolean) => ipcRenderer.invoke('codex:account-read', refresh),
  codexAccountRates: () => ipcRenderer.invoke('codex:account-rates'),
  codexLogin: () => ipcRenderer.invoke('codex:login'),
  codexLoginApiKey: (key: string) => ipcRenderer.invoke('codex:login-api-key', key),
  codexLogout: () => ipcRenderer.invoke('codex:logout'),
  codexModels: () => ipcRenderer.invoke('codex:models'),
  codexThreads: (cwd?: string) => ipcRenderer.invoke('codex:threads', cwd),
  codexStartThread: (input: unknown) => ipcRenderer.invoke('codex:start-thread', input),
  codexResumeThread: (input: unknown) => ipcRenderer.invoke('codex:resume-thread', input),
  codexStartTurn: (input: unknown) => ipcRenderer.invoke('codex:start-turn', input),
  codexInterrupt: (input: unknown) => ipcRenderer.invoke('codex:interrupt', input),
  codexServerResponse: (input: unknown) => ipcRenderer.invoke('codex:server-response', input),
  hermesStatus: (refresh?: boolean) => ipcRenderer.invoke('hermes:status', refresh),
  hermesModels: (refresh?: boolean) => ipcRenderer.invoke('hermes:models', refresh),
  hermesNewSession: (input: unknown) => ipcRenderer.invoke('hermes:new-session', input),
  hermesLoadSession: (input: unknown) => ipcRenderer.invoke('hermes:load-session', input),
  hermesSetModel: (input: unknown) => ipcRenderer.invoke('hermes:set-model', input),
  hermesPrompt: (input: unknown) => ipcRenderer.invoke('hermes:prompt', input),
  hermesCancel: (sessionId: string) => ipcRenderer.invoke('hermes:cancel', sessionId),
  hermesPermission: (input: unknown) => ipcRenderer.invoke('hermes:permission', input),
  onRoomEvent: (handler: (value: unknown) => void) => subscribe('room:event', handler),
  onOutboxChanged: (handler: (value: unknown) => void) => subscribe('room:outbox', handler),
  onRoomConnection: (handler: (value: unknown) => void) => subscribe('room:connection', handler),
  onAppError: (handler: (value: unknown) => void) => subscribe('app:error', handler),
  onAgentActivity: (handler: (value: unknown) => void) => subscribe('agent:activity', handler),
  onCodexRequest: (handler: (value: unknown) => void) => subscribe('codex:request', handler),
  onHermesRequest: (handler: (value: unknown) => void) => subscribe('hermes:request', handler),
  onCodexEvent: (handler: (value: unknown) => void) => subscribe('codex:event', handler),
  onHermesEvent: (handler: (value: unknown) => void) => subscribe('hermes:event', handler),
});
